//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS_BSS_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationId { get; set; }
        public int ApplicationNumber { get; set; }
        public int CustomerId { get; set; }
        public int ServiceId { get; set; }
        public int TypeOfServiceId { get; set; }
        public int VidOfServiceId { get; set; }
        public int StatusId { get; set; }
        public int TypeOfEquipmentId { get; set; }
        public int ProblemId { get; set; }
        public int DiscountId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public Nullable<System.DateTime> DateOfClose { get; set; }
    
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Problem Problem { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual TypeOfEquipment TypeOfEquipment { get; set; }
        public virtual TypeOfService TypeOfService { get; set; }
        public virtual VidOfService VidOfService { get; set; }

        
    }
}
