//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS_BSS_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedApplication
    {
        public int CompletedApplicationId { get; set; }
        public int StaffId { get; set; }
        public int CustomerId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
