//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS_BSS_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Application = new HashSet<Application>();
            this.CompletedApplication = new HashSet<CompletedApplication>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int CustomerId { get; set; }
        public string FIOCustomer { get; set; }
        public int PersonalAccountCustom { get; set; }
        public int Tariff { get; set; }
        public string NumberPhone { get; set; }
        public int RoleId { get; set; }
        public decimal BalanceSubscriber { get; set; }
        public Nullable<decimal> Arrear { get; set; }
        public int ContractNumber { get; set; }
        public int ServiceId { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime DateOfIssueOfThePassport { get; set; }
        public string WhoIssuedThePassport { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateOfTheAppeal { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompletedApplication> CompletedApplication { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Role Role { get; set; }
        public virtual Service Service { get; set; }
        public virtual Tariff Tariff1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
