//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS_BSS_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int EquipmentId { get; set; }
        public string InventoryNumber { get; set; }
        public string NameOfEquipment { get; set; }
        public string SerialNumber { get; set; }
        public int TypeOfEquipmentId { get; set; }
        public string Condition { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string LeasedPurchased { get; set; }
        public string Address { get; set; }
        public int InstalledByWhom { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual TypeOfEquipment TypeOfEquipment { get; set; }
    }
}
